import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <main>
      <div className="sidebar-left">
        Left
      </div>
      {children}
      <div className="sidebar-right">
        Right
      </div>
    </main>


  );
}
